configuration:
  width: 800
  height: 800
  luminosity-label: '%lumi% fb^{-1} (8 TeV)'
  experiment: "CMS"
  extra-label: "Simulation preliminary"
  root: '@root@'
  luminosity: @lumi@ 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: '@text@'
      position: [0.22, 0.9]
      size: 24

files:

  'TTJets_MSDecays_JpsiFilter_166_5.root':
    type: signal
    cross-section: 245.8
#    generated-events: 2537451 
    generated-events: 3387481 
    line-color: 419
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=166.5 GeV'

  'TTJets_MSDecays_JpsiFilter_169_5.root':
    type: signal
    cross-section: 245.8
#    generated-events: 1909822
    generated-events: 2549600 
    line-color: 862
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=169.5 GeV'

  'TTJets_MSDecays_JpsiFilter_171_5.root':
    type: signal
    cross-section: 245.8
#    generated-events: 1803768
    generated-events: 2405277 
    line-color: 602
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=171.5 GeV'

  'TTJets_MSDecays_JpsiFilter_172_5.root':
    type: signal
    cross-section: 245.8
#    generated-events: 4037468
    generated-events: 5380767 
    line-color: 877
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=172.5 GeV'

  'TTJets_MSDecays_JpsiFilter_173_5.root':
    type: signal
    cross-section: 245.8
#    generated-events: 1775180
    generated-events: 2365831 
    line-color: 907
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=173.5 GeV'

  'TTJets_MSDecays_JpsiFilter_175_5.root':
    type: signal
    cross-section: 245.8 
#    generated-events: 2878798
    generated-events: 3834254 
    line-color: 807
    line-type: 1
    line-width: 3
    legend: 'm_{top}=175.5 GeV'

  'TTJets_MSDecays_JpsiFilter_178_5.root':
    type: signal
    cross-section: 245.8 
#    generated-events: 1836496
    generated-events: 2451711
    line-color: 800
    line-type: 1
    line-width: 3
    legend: 'm_{top}=178.5 GeV'

  'TTJets_SemiLeptMGDecays.root':
    type: mc
    cross-section: 107.6722
    generated-events: 31004465
    legend: 't#bar{t} semi-lept.'
    fill-color: 633 
    order: 2

  'TTJets_FullLeptMGDecays.root':
    type: mc
    cross-section: 25.8031
    generated-events: 12011428
    legend: 't#bar{t} dilept.'
    fill-color: 625 
    order: 1

  'TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    legend: 't#bar{t} hadronic'
    fill-color: 616 
    order: 0

plots:
  ##"Histo":
    ##save-extensions: ["pdf","C","jpg","eps"]
    ##rebin: 1
    ##show-ratio: false
    ##show-errors: true
    ##log-y: true
    ##x-axis-range: [,]
    ##y-axis-range: [,]

  "Event-yields":
    no-data: true
    y-axis-format: "%1%"
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-range: [10, 4e3]
    y-axis-show-zero: true

  "NMuons-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NElectrons-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets20-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-cuts":
    no-data: true
    y-axis-format: "%1% / (%2$.3f GeV)"
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJpsi-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts":
    no-data: true
    y-axis-format: "%1% / (%2$.2f cm)"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts":
    no-data: true
    y-axis-format: "%1% / %2$.3f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-range-axis: [0, 250]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 30]
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    x-axis-range: [0, 0.2]
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets20":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets20":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets20":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets20":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 100]
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets20":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 30]
    save-extensions: ["pdf","C","jpg","eps"]
  "MtW":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis: "W transverse mass (GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NVertices":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksVertices":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-large":
    no-data: true
    y-axis-format: "%1% / (%2$.3f GeV)"
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.3f GeV)"
    y-axis-show-zero: true
    #show-ratio: true
    show-ratio: false
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.2f cm)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-zoom":
    no-data: true
    y-axis-format: "%1% / (%2$.4f cm)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "SigmaLJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.5f cm)"
    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.3f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtFracJpsiJet":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "DPhiJpsiIsoLept":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-range: [0, 60]
    save-extensions: ["pdf","C","jpg","eps"]
  "DRJpsiIsoLept":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "PtMuJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaMuJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMuJpsi":
    no-data: true
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 50]
    save-extensions: ["pdf","C","jpg","eps"]

  "PtJetJpsi":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChMuEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEMEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChHadEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEFracJetJpsi":
    no-data: true
    legend-position: [0.22, 0.45, 0.4, 0.8]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEMEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NHadEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEFracJetJpsi":
    no-data: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "MTriLept-allPair":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtTriLept":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    
  "bjjMass":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "WMass":
    no-data: true
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

legend:
  position: [0.72, 0.55, 0.9, 0.9]
