configuration:
  width: 800
  height: 800
  luminosity-label: '%lumi% fb^{-1} (8 TeV)'
  experiment: "CMS"
  extra-label: "Simulation preliminary"
  root: 'MyAnaSkim'
  luminosity: 19697 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: 'l + Jets channel'
      position: [0.22, 0.9]
      size: 24

files:

  'TTJets_MSDecays_JpsiFilter_166_5.root':
    type: signal
    cross-section: 245.8
    generated-events: 2537451 
    line-color: 419
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=166.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_169_5.root':
    type: signal
    cross-section: 245.8
    generated-events: 1909822
    line-color: 862
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=169.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_171_5.root':
    type: signal
    cross-section: 245.8
    generated-events: 1803768
    line-color: 602
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=171.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_172_5.root':
    type: signal
    cross-section: 245.8
    generated-events: 4037468
    line-color: 877
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=172.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_173_5.root':
    type: signal
    cross-section: 245.8
    generated-events: 1775180
    line-color: 907
    line-type: 1 
    line-width: 3
    legend: 'm_{top}=173.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_175_5.root':
    type: signal
    cross-section: 245.8 
    generated-events: 2878798
    line-color: 807
    line-type: 1
    line-width: 3
    legend: 'm_{top}=175.5 GeV/c^{2}'

  'TTJets_MSDecays_JpsiFilter_178_5.root':
    type: signal
    cross-section: 245.8 
    generated-events: 1836496
    line-color: 800
    line-type: 1
    line-width: 3
    legend: 'm_{top}=178.5 GeV/c^{2}'

  'TTJets_SemiLeptMGDecays.root':
    type: mc
    cross-section: 107.6722
    generated-events: 31004465
    legend: 't#bar{t} semi-lept.'
    fill-color: 2 
    order: 2

  'TTJets_FullLeptMGDecays.root':
    type: mc
    cross-section: 25.8031
    generated-events: 12011428
    legend: 't#bar{t} dilept.'
    fill-color: 3 
    order: 1

  'TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    legend: 't#bar{t} hadronic'
    fill-color: 4 
    order: 0

plots:
  ##"Histo":
    ##save-extensions: ["pdf","C","jpg","eps"]
    ##rebin: 1
    ##show-ratio: false
    ##show-errors: true
    ##log-y: true
    ##x-axis-range: [,]
    ##y-axis-range: [,]

  "Event-yields":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-range: [20, 2e8]
    y-axis-show-zero: true

  "NMuons-cuts":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NElectrons-cuts":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets20-cuts":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20-cuts":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-cuts":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJpsi-cuts":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi-cuts":
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 80]
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    x-axis-range: [0, 0.2]
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-range: [0, 200]
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 70]
    save-extensions: ["pdf","C","jpg","eps"]
  "MtW":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NVertices":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksVertices":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NJpsi":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 80]
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-zoom":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "SigmaLJpsi":
    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtFracJpsiJet":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "DPhiJpsiIsoLept":
    y-axis-range: [0, 200]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "DRJpsiIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "PtMuJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaMuJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMuJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 110]
    save-extensions: ["pdf","C","jpg","eps"]

  "PtJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChMuEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "MTriLept-allPair":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtTriLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    
  "bjjMass":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "WMass":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

legend:
  position: [0.72, 0.55, 0.9, 0.9]
