configuration:
  width: 600
  height: 600
  luminosity-label: '%lumi% fb^{-1} (8 TeV)'
  experiment: "CMS"
  extra-label: "Simulation preliminary"
  root: 'MyAnaEl'
  luminosity: 19690 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: 'e + Jets channel'
      position: [0.22, 0.9]
      size: 24

files:
  'ElectronHadASingleElectronBCD.root':
    type: data
    legend: "Data"

  'TTJets_SemiLeptMGDecays.root':
    type: signal
    cross-section: 107.6722
    generated-events: 31004465
    legend: 't#bar{t} semi-lept.'
    fill-color: 2 
    order: 7

  'TTJets_FullLeptMGDecays.root':
    type: signal
    cross-section: 25.8031
    generated-events: 12011428
    legend: 't#bar{t} dilept.'
    fill-color: 3 
    order: 6

  'TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    legend: 't#bar{t} hadronic'
    fill-color: 4 
    order: 5

  'T_s-channel.root':
    type: mc
    cross-section: 3.79
    generated-events: 259961
    group: sto
    order: 4

  'T_t-channel.root':
    type: mc
    cross-section: 56.4
    generated-events: 3758227
    group: sto
    order: 4

  'T_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 497658
    group: sto
    order: 4

  'Tbar_s-channel.root':
    type: mc
    cross-section: 1.76
    generated-events: 139974
    group: sto
    order: 4

  'Tbar_t-channel.root':
    type: mc
    cross-section: 30.7
    generated-events: 1935072
    group: sto
    order: 4

  'Tbar_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 493460
    group: sto
    order: 4

  'TTWJets.root':
    type: mc
    cross-section: 0.2149
    generated-events: 196046
    group: tto
    order: 3

  'TTWWJets.root':
    type: mc
    cross-section: 0.002037
    generated-events: 217820
    group: tto
    order: 3

  'TTZJets.root':
    type: mc
    cross-section: 0.172
    generated-events: 210160
    group: tto
    order: 3

  'WW-incl.root':
    type: mc
    cross-section: 54.838
    generated-events: 10000431
    group: dib
    order: 2

  'WZ-incl.root':
    type: mc
    cross-section: 33.21
    generated-events: 10000283
    group: dib
    order: 2

  'ZZ-incl.root':
    type: mc
    cross-section: 17.654
    generated-events: 9799908
    group: dib
    order: 2

  'DY1JetsToLL_M-50.root':
    type: mc
    cross-section: 561.0
    generated-events: 24045248
    group: zll
    order: 1

  'DY2JetsToLL_M-50.root':
    type: mc
    cross-section: 181.0
    generated-events: 21852156
    group: zll
    order: 1

  'DY3JetsToLL_M-50.root':
    type: mc
    cross-section: 51.1
    generated-events: 11015445
    group: zll
    order: 1

  'DY4JetsToLL_M-50.root':
    type: mc
    cross-section: 23.04
    generated-events: 6402827
    group: zll
    order: 1

  'W1JetsToLNu.root':
    type: mc
    cross-section: 5562.36 
    generated-events: 23141598
    group: wln
    order: 0

  'W2JetsToLNu.root':
    type: mc
    cross-section: 1802.62
    generated-events: 34044921
    group: wln
    order: 0

  'W3JetsToLNu.root':
    type: mc
    cross-section: 534.604
    generated-events: 15539503
    group: wln
    order: 0

  'W4JetsToLNu.root':
    type: mc
    cross-section: 220.434
    generated-events: 13382803
    group: wln
    order: 0

plots:
  ##"Histo":
    ##save-extensions: ["pdf","C","jpg","eps"]
    ##rebin: 1
    ##show-ratio: false
    ##show-errors: true
    ##log-y: true
    ##x-axis-range: [,]
    ##y-axis-range: [,]

  "PUAfter":
    save-extensions: ["pdf","C","jpg","eps"]

  "Event-yields":
    save-extensions: ["pdf","C","jpg","eps"]

  "NMuons-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "NElectrons-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets20-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "NJpsi-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts":
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts":
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20":
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30":
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40":
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50":
    save-extensions: ["pdf","C","jpg","eps"]

  "PtLeadJet1":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaLeadJet1":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiLeadJet1":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtLeadJet2":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaLeadJet2":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiLeadJet2":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtLeadJet3":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaLeadJet3":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiLeadJet3":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtLeadJet4":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaLeadJet4":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiLeadJet4":
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":
    save-extensions: ["pdf","C","jpg","eps"]
  "MtW":
    save-extensions: ["pdf","C","jpg","eps"]

  "NVertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "XVertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "YVertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "ZVertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "NdofVertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "NormChi2Vertices":
    save-extensions: ["pdf","C","jpg","eps"]
  "IsFakeVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksVertices":
    save-extensions: ["pdf","C","jpg","eps"]

  "XLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "YLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "ZLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "NdofLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "NormChi2LeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "IsFakeLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksLeadingVertex":
    save-extensions: ["pdf","C","jpg","eps"]

  "NJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-zoom":
    save-extensions: ["pdf","C","jpg","eps"]
  "SigmaLJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtFracJpsiJet":
    save-extensions: ["pdf","C","jpg","eps"]

  "DPhiJpsiIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  "DRJpsiIsoLept":
    save-extensions: ["pdf","C","jpg","eps"]
  
  "PtMuJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaMuJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMuJpsi":
    save-extensions: ["pdf","C","jpg","eps"]
  
  "MTriLept-allPair":
    save-extensions: ["pdf","C","jpg","eps"]
  "PtTriLept":
    save-extensions: ["pdf","C","jpg","eps"]
    
  "bjjMass":
    save-extensions: ["pdf","C","jpg","eps"]
  "WMass":
    save-extensions: ["pdf","C","jpg","eps"]

legend:
    position: [0.7, 0.65, 0.9, 0.9]

groups:
  sto:
    legend: 'single top'
    fill-color: 28

  tto:
    legend: 't#bar{t} other'
    fill-color: 625

  dib:
    legend: 'WW, WZ, ZZ'
    fill-color: 5

  zll:
    legend: 'Z + jets'
    fill-color: 870

  wln:
    legend: 'W #rightarrow l#nu + jets'
    fill-color: 33

