configuration:
  width: 800
  height: 800
  luminosity-label: '(8 TeV)'
  experiment: "CMS"
  extra-label: "Preliminary"
  root: 'MyAnaMu'
  luminosity: 19705 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: 'X-check data'
      position: [0.22, 0.9]
      size: 24

files:
  'MuHadASingleMuBCD.root':
    type: data
    legend: "@muChannel@"
    marker-color: 46
    line-color: 46
    line-width: 3

  '../MyAnaEl/ElectronHadASingleElectronBCD.root':
    type: signal
    cross-section: 1
    generated-events: 19690 
    legend: "@elChannel@"
    marker-type: 20
    marker-color: 38
    marker-size: 1
    line-type: 0
    line-color: 38
    line-width: 3
    fill-type: 0
    drawing-options: 'P'
    legend-style: 'P'

plots:
  ##"Histo":
    ##save-extensions: ["pdf","C","jpg","eps"]
    ##rebin: 1
    ##show-ratio: false
    ##show-errors: true
    ##log-y: true
    ##x-axis-range: [,]
    ##y-axis-range: [,]

  "Event-yields":
    y-axis-format: "%1%"
    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-range: [1e2, 1e3]
    y-axis-show-zero: true

  "NMuons-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "Number of isolated #mu (before cut)"
  "NElectrons-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "Number of isolated e (before cut)"
  "NJets20-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-cuts":
    y-axis-format: "%1% / (%2$.3f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NJpsi-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi-cuts":
    y-axis-format: "%1% / %2$.1f"
    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts":
    y-axis-format: "%1% / (%2$.2f cm)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts":
    y-axis-format: "%1% / %2$.3f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "Number of leading leptons"
  "PtIsoLept":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "p_{T}(leading lepton) (GeV)"
  "EtaIsoLept":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "#eta(leading lepton)"
  "PhiIsoLept":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "#phi(leading lepton)"
  "PfIsoIsoLept":
    show-ratio: false
    x-axis-range: [0, 0.2]
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "lepton isolation"

  "NJets20":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets20":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets20":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets20":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets20":
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MtW":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis: "W transverse mass (GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NVertices":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksVertices":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NJpsi":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-large":
    y-axis-format: "%1% / (%2$.3f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi":
    y-axis-format: "%1% / (%2$.3f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJpsi":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi":
    y-axis-format: "%1% / (%2$.2f cm)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-zoom":
    y-axis-format: "%1% / (%2$.4f cm)"
    y-axis-range: [0, 15]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "SigmaLJpsi":
    y-axis-format: "%1% / (%2$.5f cm)"
    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi":
    y-axis-format: "%1% / %2$.3f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PtFracJpsiJet":
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "DPhiJpsiIsoLept":
    y-axis-range: [0, 60]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "#Delta#phi (J/#psi-leading lepton)"
  "DRJpsiIsoLept":
    y-axis-range: [0, 60]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "#DeltaR (J/#psi-leading lepton)"
  
  "PtMuJpsi":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaMuJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMuJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]

  "PtJetJpsi":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChMuEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEFracJetJpsi":
    legend-position: [0.22, 0.72, 0.52, 0.8]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "MTriLept-allPair":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "M(J/#psi+l) (GeV)"
  "PtTriLept":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis: "p_{T}(J/#psi+l) (GeV)"
    
  "bjjMass":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "WMass":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

legend:
    position: [0.6, 0.82, 0.9, 0.9]

groups:
  sto:
    legend: 'single top'
    fill-color: 28

  tto:
    legend: 't#bar{t} other'
    fill-color: 625

  dib:
    legend: 'WW, WZ, ZZ'
    fill-color: 5

  zll:
    legend: 'Z + jets'
    fill-color: 870

  wln:
    legend: 'W #rightarrow l#nu + jets'
    fill-color: 33
