configuration:
  width: 800
  height: 800
  luminosity-label: '%lumi% fb^{-1} (8 TeV)'
  experiment: "CMS"
  extra-label: "Preliminary"
  root: '@root@'
  luminosity: @lumi@ 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: '@text@'
      position: [0.22, 0.9]
      size: 24

files:
  '@dataFile@':
    type: data
    legend: "Data"

  'TTJets_SemiLeptMGDecays.root':
    type: mc
    cross-section: 107.6722
    generated-events: 31004465
    legend: 't#bar{t} semi-lept.'
    fill-color: 633 
    order: 7

  'TTJets_FullLeptMGDecays.root':
    type: mc
    cross-section: 25.8031
    generated-events: 12011428
    legend: 't#bar{t} dilept.'
    fill-color: 625 
    order: 6

  'TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    legend: 't#bar{t} hadronic'
    fill-color: 616 
    order: 5

  'T_s-channel.root':
    type: mc
    cross-section: 3.79
    generated-events: 259961
    group: sto
    order: 4

  'T_t-channel.root':
    type: mc
    cross-section: 56.4
    generated-events: 3758227
    group: sto
    order: 4

  'T_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 497658
    group: sto
    order: 4

  'Tbar_s-channel.root':
    type: mc
    cross-section: 1.76
    generated-events: 139974
    group: sto
    order: 4

  'Tbar_t-channel.root':
    type: mc
    cross-section: 30.7
    generated-events: 1935072
    group: sto
    order: 4

  'Tbar_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 493460
    group: sto
    order: 4

  'TTWJets.root':
    type: mc
    cross-section: 0.2149
    generated-events: 196046
    group: tto
    order: 3

  'TTWWJets.root':
    type: mc
    cross-section: 0.002037
    generated-events: 217820
    group: tto
    order: 3

  'TTZJets.root':
    type: mc
    cross-section: 0.172
    generated-events: 210160
    group: tto
    order: 3

  'WW-incl.root':
    type: mc
    cross-section: 56.0
##cross-section: 54.838
    generated-events: 10000431
    group: dib
    order: 2

  'WZ-incl.root':
    type: mc
    cross-section: 33.6
##cross-section: 33.21
    generated-events: 10000283
    group: dib
    order: 2

  'ZZ-incl.root':
    type: mc
    cross-section: 7.6
##cross-section: 17.654
    generated-events: 9799908
    group: dib
    order: 2

  'DY1JetsToLL_M-50.root':
    type: mc
    cross-section: 666.3
##cross-section: 561.0
    generated-events: 24045248
    group: zll
    order: 1

  'DY2JetsToLL_M-50.root':
    type: mc
    cross-section: 215.0
##cross-section: 181.0
    generated-events: 21852156
    group: zll
    order: 1

  'DY3JetsToLL_M-50.root':
    type: mc
    cross-section: 60.7
##cross-section: 51.1
    generated-events: 11015445
    group: zll
    order: 1

  'DY4JetsToLL_M-50.root':
    type: mc
    cross-section: 27.3
##cross-section: 23.04
    generated-events: 6402827
    group: zll
    order: 1

  'W1JetsToLNu.root':
    type: mc
    cross-section: 6662.8 
##cross-section: 5562.36 
    generated-events: 23141598
    group: wln
    order: 0

  'W2JetsToLNu.root':
    type: mc
    cross-section: 2159.2
##cross-section: 1802.62
    generated-events: 34044921
    group: wln
    order: 0

  'W3JetsToLNu.root':
    type: mc
    cross-section: 640.4
##cross-section: 534.604
    generated-events: 15539503
    group: wln
    order: 0

  'W4JetsToLNu.root':
    type: mc
    cross-section: 264.0
##cross-section: 220.434
    generated-events: 13382803
    group: wln
    order: 0

plots:
  ##"Histo":
    ##save-extensions: ["pdf","C","jpg","eps"]
    ##rebin: 1
    ##show-ratio: false
    ##show-errors: true
    ##log-y: true
    ##x-axis-range: [,]
    ##y-axis-range: [,]

  "Event-yields":
    y-axis-format: "%1%"
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-range: [10, 4e3]
    y-axis-show-zero: true
  "Decay":
    y-axis-format: "%1%"
    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-show-zero: true

  "NMuons-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NElectrons-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets20-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-cuts":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJpsi-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi-cuts":
    y-axis-format: "%1% / %2$.1f"
    log-y: true
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts":
    y-axis-format: "%1% / (%2$.2f cm)"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-cuts-zoom":
    y-axis-format: "%1% / (%2$.4f cm)"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts":
    y-axis-format: "%1% / %2$.3f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi-cuts-zoom":
    y-axis-format: "%1%"
    log-x: true
    log-y: true
    y-axis-range: [1, 2e3]
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "DRJpsiIsoLept-cuts":
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    x-axis-range: [0, 250]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 30]
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    x-axis-range: [0, 0.2]
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets20":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets20":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets20":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets20":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 100]
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets20":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NCsvJets20":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets40":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets50":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 30]
    save-extensions: ["pdf","C","jpg","eps"]
  "MtW":
    y-axis-format: "%1% / (%2$.0f GeV/c^{2})"
    x-axis: "W transverse mass (GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NVertices":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NTracksVertices":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NJpsi":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi-large":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "MJpsi":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJpsi":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Chi2Jpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi":
    y-axis-format: "%1% / (%2$.2f cm)"
    log-y: true
    y-axis-show-zero: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LJpsi-zoom":
    y-axis-format: "%1% / (%2$.4f cm)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "SigmaLJpsi":
    y-axis-format: "%1% / (%2$.5f cm)"
    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "LOverSigmaJpsi":
    y-axis-format: "%1% / %2$.3f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtFracJpsiJet":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "DPhiJpsiIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-range: [0, 60]
    save-extensions: ["pdf","C","jpg","eps"]
  "DRJpsiIsoLept":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "PtMuJpsi":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaMuJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMuJpsi":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 50]
    save-extensions: ["pdf","C","jpg","eps"]

  "PtJetJpsi":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChMuEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "ChEFracJetJpsi":
    legend-position: [0.22, 0.45, 0.4, 0.8]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEMEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NHadEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NEFracJetJpsi":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  
  "MTriLept-allPair":
    y-axis-format: "%1% / (%2$.0f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtTriLept":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    
  "bjjMass":
    y-axis-format: "%1% / (%2$.0f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "WMass":
    y-axis-format: "%1% / (%2$.0f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

legend:
  position: [0.72, 0.55, 0.9, 0.9]

groups:
  sto:
    legend: 'single top'
    fill-color: 618

  tto:
    legend: 't#bar{t} other'
    fill-color: 797

  dib:
    legend: 'WW, WZ, ZZ'
    fill-color: 400

  zll:
    legend: 'Z + jets'
    fill-color: 868

  wln:
    legend: 'W #rightarrow l#nu + jets'
    fill-color: 858
