configuration:
  width: 800
  height: 800
  luminosity-label: '%lumi% fb^{-1} (8 TeV)'
  experiment: "CMS"
  extra-label: "Simulation preliminary"
  root: 'MyAnaMu'
  luminosity: 19690 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: '@text@'
      position: [0.22, 0.9]
      size: 24

files:
  'MuHadASingleMuBCD.root':
    type: data
    legend: "Data"
  '../MyAnaEl/ElectronHadASingleElectronBCD.root':
    type: data

  'TTJets_SemiLeptMGDecays.root':
    type: mc
    cross-section: 107.6722
    generated-events: 31004465
    group: tts
    order: 7
  '../MyAnaEl/TTJets_SemiLeptMGDecays.root':
    type: mc
    cross-section: 107.6722
    generated-events: 31004465
    group: tts
    order: 7

  'TTJets_FullLeptMGDecays.root':
    type: mc
    cross-section: 25.8031
    generated-events: 12011428
    group: ttd
    order: 6
  '../MyAnaEl/TTJets_FullLeptMGDecays.root':
    type: mc
    cross-section: 25.8031
    generated-events: 12011428
    group: ttd
    order: 6

  'TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    group: tth
    order: 5
  '../MyAnaEl/TTJets_HadronicMGDecays.root':
    type: mc
    cross-section: 112.325
    generated-events: 31223821
    group: tth
    order: 5

  'T_s-channel.root':
    type: mc
    cross-section: 3.79
    generated-events: 259961
    group: sto
    order: 4
  '../MyAnaEl/T_s-channel.root':
    type: mc
    cross-section: 3.79
    generated-events: 259961
    group: sto
    order: 4

  'T_t-channel.root':
    type: mc
    cross-section: 56.4
    generated-events: 3758227
    group: sto
    order: 4
  '../MyAnaEl/T_t-channel.root':
    type: mc
    cross-section: 56.4
    generated-events: 3758227
    group: sto
    order: 4

  'T_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 497658
    group: sto
    order: 4
  '../MyAnaEl/T_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 497658
    group: sto
    order: 4

  'Tbar_s-channel.root':
    type: mc
    cross-section: 1.76
    generated-events: 139974
    group: sto
    order: 4
  '../MyAnaEl/Tbar_s-channel.root':
    type: mc
    cross-section: 1.76
    generated-events: 139974
    group: sto
    order: 4

  'Tbar_t-channel.root':
    type: mc
    cross-section: 30.7
    generated-events: 1935072
    group: sto
    order: 4
  '../MyAnaEl/Tbar_t-channel.root':
    type: mc
    cross-section: 30.7
    generated-events: 1935072
    group: sto
    order: 4

  'Tbar_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 493460
    group: sto
    order: 4
  '../MyAnaEl/Tbar_tW-channel.root':
    type: mc
    cross-section: 11.1
    generated-events: 493460
    group: sto
    order: 4

  'TTWJets.root':
    type: mc
    cross-section: 0.2149
    generated-events: 196046
    group: tto
    order: 3
  '../MyAnaEl/TTWJets.root':
    type: mc
    cross-section: 0.2149
    generated-events: 196046
    group: tto
    order: 3

  'TTWWJets.root':
    type: mc
    cross-section: 0.002037
    generated-events: 217820
    group: tto
    order: 3
  '../MyAnaEl/TTWWJets.root':
    type: mc
    cross-section: 0.002037
    generated-events: 217820
    group: tto
    order: 3

  'TTZJets.root':
    type: mc
    cross-section: 0.172
    generated-events: 210160
    group: tto
    order: 3
  '../MyAnaEl/TTZJets.root':
    type: mc
    cross-section: 0.172
    generated-events: 210160
    group: tto
    order: 3

  'WW-incl.root':
    type: mc
    cross-section: 56.0
##cross-section: 54.838
    generated-events: 10000431
    group: dib
    order: 2
  '../MyAnaEl/WW-incl.root':
    type: mc
    cross-section: 56.0
##cross-section: 54.838
    generated-events: 10000431
    group: dib
    order: 2

  'WZ-incl.root':
    type: mc
    cross-section: 33.6
##cross-section: 33.21
    generated-events: 10000283
    group: dib
    order: 2
  '../MyAnaEl/WZ-incl.root':
    type: mc
    cross-section: 33.6
##cross-section: 33.21
    generated-events: 10000283
    group: dib
    order: 2

  'ZZ-incl.root':
    type: mc
    cross-section: 7.6
##cross-section: 17.654
    generated-events: 9799908
    group: dib
    order: 2
  '../MyAnaEl/ZZ-incl.root':
    type: mc
    cross-section: 7.6
##cross-section: 17.654
    generated-events: 9799908
    group: dib
    order: 2

  'DY1JetsToLL_M-50.root':
    type: mc
    cross-section: 666.3
##cross-section: 561.0
    generated-events: 24045248
    group: zll
    order: 1
  '../MyAnaEl/DY1JetsToLL_M-50.root':
    type: mc
    cross-section: 666.3
##cross-section: 561.0
    generated-events: 24045248
    group: zll
    order: 1

  'DY2JetsToLL_M-50.root':
    type: mc
    cross-section: 215.0
##cross-section: 181.0
    generated-events: 21852156
    group: zll
    order: 1
  '../MyAnaEl/DY2JetsToLL_M-50.root':
    type: mc
    cross-section: 215.0
##cross-section: 181.0
    generated-events: 21852156
    group: zll
    order: 1

  'DY3JetsToLL_M-50.root':
    type: mc
    cross-section: 60.7
##cross-section: 51.1
    generated-events: 11015445
    group: zll
    order: 1
  '../MyAnaEl/DY3JetsToLL_M-50.root':
    type: mc
    cross-section: 60.7
##cross-section: 51.1
    generated-events: 11015445
    group: zll
    order: 1

  'DY4JetsToLL_M-50.root':
    type: mc
    cross-section: 27.3
##cross-section: 23.04
    generated-events: 6402827
    group: zll
    order: 1
  '../MyAnaEl/DY4JetsToLL_M-50.root':
    type: mc
    cross-section: 27.3
##cross-section: 23.04
    generated-events: 6402827
    group: zll
    order: 1

  'W1JetsToLNu.root':
    type: mc
    cross-section: 6662.8 
##cross-section: 5562.36 
    generated-events: 23141598
    group: wln
    order: 0
  '../MyAnaEl/W1JetsToLNu.root':
    type: mc
    cross-section: 6662.8 
##cross-section: 5562.36 
    generated-events: 23141598
    group: wln
    order: 0

  'W2JetsToLNu.root':
    type: mc
    cross-section: 2159.2
##cross-section: 1802.62
    generated-events: 34044921
    group: wln
    order: 0
  '../MyAnaEl/W2JetsToLNu.root':
    type: mc
    cross-section: 2159.2
##cross-section: 1802.62
    generated-events: 34044921
    group: wln
    order: 0

  'W3JetsToLNu.root':
    type: mc
    cross-section: 640.4
##cross-section: 534.604
    generated-events: 15539503
    group: wln
    order: 0
  '../MyAnaEl/W3JetsToLNu.root':
    type: mc
    cross-section: 640.4
##cross-section: 534.604
    generated-events: 15539503
    group: wln
    order: 0

  'W4JetsToLNu.root':
    type: mc
    cross-section: 264.0
##cross-section: 220.434
    generated-events: 13382803
    group: wln
    order: 0
  '../MyAnaEl/W4JetsToLNu.root':
    type: mc
    cross-section: 264.0
##cross-section: 220.434
    generated-events: 13382803
    group: wln
    order: 0

plots:
  "NMuons-cuts":  
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NElectrons-cuts":  
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "NJets30-cuts":  
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "N-b-jets-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":  
    y-axis-format: "%1% / %2$.0f"
    x-axis: "Number of leading leptons"
    show-ratio: true
    fit-ratio: false
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":  
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    x-axis: "p_{T}(leading lepton) (GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":  
    y-axis-format: "%1% / %2$.1f"
    x-axis: "#eta(leading lepton)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":  
    y-axis-format: "%1% / %2$.1f"
    x-axis: "#phi(leading lepton)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 9000]
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":  
    x-axis: "lepton isolation"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    x-axis-range: [0, 0.2]
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets30":  
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [3, 11]
  "PtJets30":  
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    x-axis-range: [0, 300]
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets30":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets30":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 40000]
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets30":  
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":  
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    y-axis-show-zero: true
    y-axis-range: [0, 8000]
    save-extensions: ["pdf","C","jpg","eps"]

  "NPrimaryVtx":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "N-b-jets":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "CSV-b-jets":
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "TransverseMomentum-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 300]
  "Eta-b-jets":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "Nch-b-jets":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "Sump-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 400]
  "VectorialSump-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 400]

  "Highestp-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 200]
  "Sum2p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 300]
  "Sum3p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 300]
  "Mass3-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R1-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R2-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R3-b-jets":
    legend-position: [0.22, 0.45, 0.4, 0.8] 
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "Highestp-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 200]
  "Sum2p-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 300]
  "Sum3p-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 300]
  "Mass3-nomu-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R1-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R2-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "R3-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "D0Mass-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    x-axis-range: [0, 5]
    ##x-axis-range: [1.6, 2.2]
    ##y-axis-range; [0, 300]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "D0Mass-zoom-b-jets":
    y-axis-show-zero: true
    y-axis-format: "%1% / (%2$.2f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "D0p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "D0pT-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 150]
  "D0eta-b-jets":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-show-zero: true
    y-axis-range: [0, 2400]

  "BMomentum-nobias-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    x-axis-range: [0, 350]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "BMass-nobias-b-jets":
    y-axis-format: "%1% / (%2$.1f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "BMomentum-D0cut-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    x-axis-range: [0, 350]
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
  "BMass-D0cut-b-jets":
    y-axis-format: "%1% / (%2$.1f GeV/c^{2})"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]

  "Muonp-nobias-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV/c)"
    show-ratio: true
    fit-ratio: true
    fit-function: "pol1"
    show-errors: true
    save-extensions: ["pdf","C","jpg","eps"]
    x-axis-range: [0, 200]

legend:
    position: [0.72, 0.55, 0.9, 0.9]

groups:
  tts:
    legend: 't#bar{t} semi-lept.'
    fill-color: 633 

  ttd:
    legend: 't#bar{t} dilept.'
    fill-color: 625 

  tth:
    legend: 't#bar{t} hadronic'
    fill-color: 616

  sto:
    legend: 'single top'
    fill-color: 618

  tto:
    legend: 't#bar{t} other'
    fill-color: 797

  dib:
    legend: 'WW, WZ, ZZ'
    fill-color: 400

  zll:
    legend: 'Z + jets'
    fill-color: 868

  wln:
    legend: 'W #rightarrow l#nu + jets'
    fill-color: 858

