configuration:
  width: 800
  height: 800
  luminosity-label: '(8 TeV)'
  experiment: "CMS"
  extra-label: "Preliminary"
  root: 'MyAnaMu'
  luminosity: 19705 
  luminosity-error: 0.026
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"  
  labels:
    - text: 'X-check data'
      position: [0.22, 0.9]
      size: 26

files:
  'MuHadASingleMuBCD.root':
    type: data
    legend: "#mu + Jets channel"
    marker-color: 46
    line-color: 46
    line-width: 3

  '../MyAnaEl/ElectronHadASingleElectronBCD.root':
    type: signal
    cross-section: 1
    generated-events: 19690 
    legend: "e + Jets channel"
    marker-type: 20
    marker-color: 38
    marker-size: 1
    line-type: 0
    line-color: 38
    line-width: 3
    fill-type: 0
    drawing-options: 'P'
    legend-style: 'P'

plots:
  "NJets30-cuts":  
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "N-b-jets-cuts":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NIsoLept":  
    y-axis-format: "%1% / %2$.0f"
    x-axis: "Number of leading leptons"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PtIsoLept":  
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis: "p_{T}(leading lepton) (GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaIsoLept":  
    y-axis-format: "%1% / %2$.1f"
    x-axis: "#eta(leading lepton)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiIsoLept":  
    y-axis-format: "%1% / %2$.1f"
    x-axis: "#phi(leading lepton)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PfIsoIsoLept":  
    x-axis: "lepton isolation"
    x-axis: "lepton isolation"
    x-axis-range: [0, 0.2]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NJets30":  
    y-axis-format: "%1% / %2$.0f"
    x-axis-range: [3, 11]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PtJets30":  
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "EtaJets30":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiJets30":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "CsvJets30":  
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "MetMet":  
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "PhiMet":  
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "NPrimaryVtx":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "N-b-jets":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "CSV-b-jets":
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "TransverseMomentum-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Eta-b-jets":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "Nch-b-jets":
    y-axis-format: "%1% / %2$.0f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Sump-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 400]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "VectorialSump-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 400]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "Highestp-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 200]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Sum2p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Sum3p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Mass3-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R1-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R2-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R3-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "Highestp-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 200]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Sum2p-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Sum3p-nomu-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "Mass3-nomu-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R1-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R2-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "R3-nomu-b-jets":
    rebin: 3
#    log-y: true
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "D0FromBMass-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV)"
    x-axis-range: [0, 5]
    ##x-axis-range: [1.6, 2.2]
    ##y-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0Mass-b-jets":
    y-axis-format: "%1% / (%2$.2f GeV)"
    x-axis-range: [0, 5]
    ##x-axis-range: [1.6, 2.2]
    ##y-axis-range: [0, 300]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0FromBMass-zoom-b-jets":
    y-axis-show-zero: true
    y-axis-format: "%1% / (%2$.2f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0Mass-zoom-b-jets":
    y-axis-show-zero: true
    y-axis-format: "%1% / (%2$.2f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0FromBp-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0p-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0pT-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 150]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "D0eta-b-jets":
    y-axis-format: "%1% / %2$.1f"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
    y-axis-show-zero: true

  "BMomentum-nobias-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 350]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "BMass-nobias-b-jets":
    y-axis-format: "%1% / (%2$.1f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "BMomentum-D0cut-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 350]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]
  "BMass-D0cut-b-jets":
    y-axis-format: "%1% / (%2$.1f GeV)"
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

  "Muonp-nobias-b-jets":
    y-axis-format: "%1% / (%2$.0f GeV)"
    x-axis-range: [0, 200]
    show-ratio: false
    save-extensions: ["pdf","C","jpg","eps"]

legend:
    position: [0.6, 0.8, 0.9, 0.9]

